Repository SoftServeInc/jira_data_process, pull requests merged in 2022-08, with the labels that each got.

#8 feature/Added github actions
  .github/workflows/main.yml
Labels: Status: Approved, MERGE READY

#5 Add configuration of renovate bot to repository
  renovate.json
Labels: Status: Approved, MERGE READY

#9 Fix build issues, update README.md file, node version, regenerate package-lock.json file
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
  renovate.json
  server/server.js
  src/components/App/App.js
  src/components/App/tests/App.test.js
  src/components/JiraQuery/JiraQuery.js
  src/components/ReceivingDataContainer/ReceivingDataContainer.js
Labels: MERGE READY

#3 Cover an app with unit tests (part #1)
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
  src/components/App/tests/App.test.js
  src/components/App/tests/__snapshots__/App.test.js.snap
  src/components/Checkboxes/GreenCheckbox/tests/GreenCheckbox.test.js
  src/components/Checkboxes/GreenCheckbox/tests/__snapshots__/GreenCheckbox.test.js.snap
  src/components/Checkboxes/tests/Checkboxes.test.js
  src/components/Checkboxes/tests/__snapshots__/Checkboxes.test.js.snap
  src/components/DataButton/tests/DataButton.test.js
  src/components/DataButton/tests/__snapshots__/DataButton.test.js.snap
  src/components/DownloadButton/tests/DownloadButton.test.js
  src/components/DownloadButton/tests/__snapshots__/DownloadButton.test.js.snap
  src/components/JiraCredentails/tests/JiraCredentials.test.js
  src/components/JiraCredentails/tests/__snapshots__/JiraCredentials.test.js.snap
  src/components/JiraQuery/tests/JiraQuery.test.js
  src/components/JiraQuery/tests/__snapshots__/JiraQuery.test.js.snap
  src/components/JiraUrl/tests/JiraUrl.test.js
  src/components/JiraUrl/tests/__snapshots__/JiraUrl.test.js.snap
  src/components/Status/tests/Status.test.js
  src/components/UploadFile/tests/UploadFile.test.js
  src/index.js
  src/serviceWorker.js
  src/setupTests.js
Labels: Status: In Progress

#6 tests/Added search integrations test
  package.json
  server/server.js
  server/tests/integration/search.test.js
  server/tests/integration/stubs.js
Labels: Status: Approved, MERGE READY

#10 [Fix BUILD]: Fix package-lock.json file
  .github/workflows/main.yml
  package-lock.json
  src/components/Checkboxes/tests/Checkboxes.test.js
  src/components/UploadFile/tests/UploadFile.test.js
Labels: MERGE READY
